<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create an invoiceCustomize, track, and _cabe8c</name>
   <tag></tag>
   <elementGuidId>9f61a82d-896c-49bb-b785-e74b2c74725d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nemo_invoiceLink > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nemo_invoiceLink']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18ac59ee-5e22-4241-98cb-d2c8d231726b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create an invoiceCustomize, track, and send invoices.</value>
      <webElementGuid>7ab3ddce-b519-4a90-be36-1e8216cb7eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nemo_invoiceLink&quot;)/div[1]</value>
      <webElementGuid>af2fd646-20c7-4c66-a6c7-f79c2a2b6ce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nemo_invoiceLink']/div</value>
      <webElementGuid>163e6c5e-144c-49c2-b22b-1cf1187ed181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[6]</value>
      <webElementGuid>f09f38b6-cc1d-4065-a9f7-b8038631e249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name, @username, email, or mobile'])[1]/following::div[6]</value>
      <webElementGuid>a8aba56c-9db6-42ab-9470-73cce123dea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div[2]/div/div/div/div/div/a/div</value>
      <webElementGuid>61c630ed-a378-4619-a729-1d7d2e67955e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Create an invoiceCustomize, track, and send invoices.' or . = 'Create an invoiceCustomize, track, and send invoices.')]</value>
      <webElementGuid>f3fae7b6-12c3-4f01-9ad9-63245e6700a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
