<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send Payments Now</name>
   <tag></tag>
   <elementGuidId>a11e7d3e-0c21-4fe4-a6e3-e0b9e523474a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-transfer-container']/div/div/form/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.css-1mggxor.vx_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e51d5b84-1e39-469a-8b06-0ab90b8124d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nemo</name>
      <type>Main</type>
      <value>send</value>
      <webElementGuid>131db6ea-388e-478f-a38b-287b1c23d428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1mggxor vx_btn</value>
      <webElementGuid>5ec7b595-8166-4347-b574-e453340c4378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send Payments Now</value>
      <webElementGuid>f08f7a93-f1f0-4faf-9ee1-ba04b670fcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-transfer-container&quot;)/div[@class=&quot;react-p2p_wrapper css-1e4troo&quot;]/div[1]/form[@class=&quot;css-16tc6h0&quot;]/button[@class=&quot;css-1mggxor vx_btn&quot;]</value>
      <webElementGuid>592c5427-9f5e-42bb-a79a-7dce6e21382a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/form/button</value>
      <webElementGuid>6bcf6bda-086f-4839-920f-dccda8901891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='user agreement'])[1]/following::button[1]</value>
      <webElementGuid>eba9e66b-56f2-4de0-8d7c-d5c157703ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>172ec424-2bf1-43eb-a7ef-03a5e86ec12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[2]/preceding::button[2]</value>
      <webElementGuid>529e6261-1442-460c-b8bc-28537f6dc697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send Payments Now']/parent::*</value>
      <webElementGuid>bd05ec9a-3d7c-4306-ab91-c2bc6ebd5988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>dc811650-c415-407d-a2b4-0ad160880047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Send Payments Now' or . = 'Send Payments Now')]</value>
      <webElementGuid>ba5fad55-94c3-43cd-928f-7127727a75e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
