<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ite</name>
   <tag></tag>
   <elementGuidId>2d76cf61-c276-467d-821e-07af3e3df692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='noteField']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#noteField</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>89cb7980-6942-42c0-8164-4d5c690df050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noteField</value>
      <webElementGuid>3c13ec16-fe73-4d6a-9835-acac038e6f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nemo</name>
      <type>Main</type>
      <value>note-field</value>
      <webElementGuid>03ebe84d-9d22-4d84-a55e-593410a7457b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>b5fde767-108d-463f-8b26-5fea23d86cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5ddc6f6-1c00-4134-859c-353c07a41933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_bjjgrz</value>
      <webElementGuid>10df5678-6372-4c1e-b0d7-b399b69b8d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ite</value>
      <webElementGuid>70d37c3f-9351-48c0-a367-78ecd5d0b2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noteField&quot;)</value>
      <webElementGuid>60dc82f1-7242-47cd-8da2-540c533670ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='noteField']</value>
      <webElementGuid>bc7cea28-947d-4004-8d2e-f6b7f185d6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/form/div/div[3]/div/textarea</value>
      <webElementGuid>838a0488-4ecf-4c00-9c69-2b13ee5a9268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Center'])[1]/following::textarea[1]</value>
      <webElementGuid>e658e6ac-1613-4ec6-8a27-37d4f76d7483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayPal Buyer Protection'])[1]/preceding::textarea[1]</value>
      <webElementGuid>6e160ffe-bfa3-4c19-9a3f-c4a947f819d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ite']/parent::*</value>
      <webElementGuid>deb1fdc4-d243-46cd-9456-b5a6efca44c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>73a735b1-e5d0-4bc4-b330-41592a504ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'noteField' and @type = 'text' and (text() = 'ite' or . = 'ite')]</value>
      <webElementGuid>4633704a-2c86-4324-8a55-3e7da2278091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
