<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_589A4529-8063-4CAA-B3A7-46DACC69259ECre_e20c6a</name>
   <tag></tag>
   <elementGuidId>04c5c3e6-bede-4cad-ad42-7a6ae61a51a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-66t19h</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='downshift-0-item-0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b5f90a65-2c81-4ded-84a9-db24480abfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemtype</name>
      <type>Main</type>
      <value>PHONE_OR_EMAIL</value>
      <webElementGuid>826db437-a607-49ea-a6f4-08f2ffa7034d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-66t19h</value>
      <webElementGuid>23724e76-5e99-488a-8356-8c6c4e8193d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>589A4529-8063-4CAA-B3A7-46DACC69259ECreated with sketchtool. Request from: nawwarahyusof123@gmail.com</value>
      <webElementGuid>41463953-9991-414f-856b-d9b662c92309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-0-item-0&quot;)/div[@class=&quot;css-66t19h&quot;]</value>
      <webElementGuid>8c86f8ae-0f7a-49be-aaf5-ae539eeb5966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='downshift-0-item-0']/div</value>
      <webElementGuid>69d67afd-c712-4902-9124-2c18abd451f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name, @username, email, or mobile'])[1]/following::div[6]</value>
      <webElementGuid>390e2356-0671-4e15-8ae8-fab331825e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request payment from'])[1]/following::div[12]</value>
      <webElementGuid>67a9f567-a013-4fd6-846a-025e2e8740cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::div[1]</value>
      <webElementGuid>0dda1001-9229-41f4-b242-7efb259a31fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request from: nawwarahyusof123@gmail.com']/parent::*</value>
      <webElementGuid>56ca4153-93cf-40ab-99a1-4b6a824c18d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div/div/div</value>
      <webElementGuid>6ab42075-bdfc-4f6b-9770-f6a9225d5168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '589A4529-8063-4CAA-B3A7-46DACC69259ECreated with sketchtool. Request from: nawwarahyusof123@gmail.com' or . = '589A4529-8063-4CAA-B3A7-46DACC69259ECreated with sketchtool. Request from: nawwarahyusof123@gmail.com')]</value>
      <webElementGuid>cc3a1c0e-91a4-4d65-a940-2f83a6aaa633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
