<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home</name>
   <tag></tag>
   <elementGuidId>768f2e5b-eca4-4c40-9268-07ef31d0c19f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='merchant-header-main-wrapper-internal']/div[2]/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-1yuw05w</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eacac8d6-1fbc-451a-afbb-11dff66f8b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1yuw05w</value>
      <webElementGuid>24068639-da11-404a-8004-e3034212117d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>header_nav_item_home</value>
      <webElementGuid>a719b583-53b5-48e3-93dd-799555f58c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.sandbox.paypal.com/mep/dashboard</value>
      <webElementGuid>cadf505d-1b7a-4865-9ff4-009c13be806f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>d3a3b7c8-5c29-4a7c-b676-1fdcf8a757d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merchant-header-main-wrapper-internal&quot;)/div[2]/div[1]/div[1]/div[1]/div[1]/a[@class=&quot;css-1yuw05w&quot;]</value>
      <webElementGuid>28122414-a9b2-43d9-9290-2f11526915b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='merchant-header-main-wrapper-internal']/div[2]/div/div/div/div/a</value>
      <webElementGuid>bb88ad7b-5517-4fae-bbed-3f9a5d4979a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Home')]</value>
      <webElementGuid>d027e306-2483-4605-b01c-5feba6fd1a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John Doe'])[1]/following::a[5]</value>
      <webElementGuid>3ed3adb4-b86b-404d-a95a-39f87ee50608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::a[5]</value>
      <webElementGuid>d8c0eb27-2503-40af-954f-53481867b52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[1]/preceding::a[1]</value>
      <webElementGuid>378a3920-26cd-432d-a4e8-179908e01a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[1]/preceding::a[1]</value>
      <webElementGuid>8acdb9b6-cb7c-4bb0-8116-17ef60f94ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>e3b7b66f-bc62-4587-b6e3-90429c5bb140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.sandbox.paypal.com/mep/dashboard')])[2]</value>
      <webElementGuid>c349545d-40f5-4c3a-860d-1f938460dcb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a</value>
      <webElementGuid>47fa75da-2410-459e-8aa9-9efa2fc8582f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.sandbox.paypal.com/mep/dashboard' and (text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>c077abb9-2e96-4957-ad5b-d7729c8a9e30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
