<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home</name>
   <tag></tag>
   <elementGuidId>78d2c1fb-4168-4106-af6a-cdf9c07a8f65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.css-1yuw05w</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='merchant-header-main-wrapper-internal']/div[2]/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7bb36ba7-f017-4fa0-9cad-2244b68c9a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1yuw05w</value>
      <webElementGuid>91be53eb-aebd-4279-921d-99964ebcc5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>header_nav_item_home</value>
      <webElementGuid>26af6cbc-5348-4726-820f-f11cc34276df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.sandbox.paypal.com/mep/dashboard</value>
      <webElementGuid>3970488d-fb1e-4787-9544-07c6d953bf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>cef87dc0-c8bb-4157-a36f-a9b51537091f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merchant-header-main-wrapper-internal&quot;)/div[2]/div[1]/div[1]/div[1]/div[1]/a[@class=&quot;css-1yuw05w&quot;]</value>
      <webElementGuid>1d80f967-8dd1-4fc7-9efa-474727eb7e97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='merchant-header-main-wrapper-internal']/div[2]/div/div/div/div/a</value>
      <webElementGuid>1e19750f-c3e0-4839-8798-5e151c903a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Home')]</value>
      <webElementGuid>5f708308-dd77-4521-afd1-1ad21d325ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John Doe'])[1]/following::a[5]</value>
      <webElementGuid>57e461b6-af25-4b0f-afc1-7e98cf45138b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::a[5]</value>
      <webElementGuid>bb0cc5a4-06aa-44a8-8d72-5f1373a17f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[1]/preceding::a[1]</value>
      <webElementGuid>d74c6d92-c1b3-46fc-8fe1-944d1dbd1991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[1]/preceding::a[1]</value>
      <webElementGuid>0b2ca97f-3f2b-4b39-a694-d27be7f703ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>6475d917-0430-4b24-91db-0beae7c644fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.sandbox.paypal.com/mep/dashboard')])[2]</value>
      <webElementGuid>0edc9961-9238-4522-bf7a-0521776b9e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a</value>
      <webElementGuid>d6e52746-4fa7-4f84-a3ab-52aa4d64ac10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.sandbox.paypal.com/mep/dashboard' and (text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>185b525a-aa95-4910-8646-650468509574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
