<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address or name_combo_t_NO_NAME</name>
   <tag></tag>
   <elementGuidId>5e9da485-94cd-4201-baca-279340627c4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combo_txt_combobox_item_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='combo_txt_combobox_item_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>baee4735-ac79-44d2-a551-37ba42051668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_text-input__control___3-14-1 ppvx_text-input__control--icon-right___3-14-1</value>
      <webElementGuid>9ab2da00-94c0-4f41-97cc-82c9447980d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>combo_t_NO_NAME</value>
      <webElementGuid>7bda0db1-c450-4350-8ad8-165f1b52900d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combo_txt_combobox_item_0</value>
      <webElementGuid>cc30dc28-478c-4de0-a07a-486f6a710a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f83e4d75-e115-457f-941d-46738a7c7705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>516355d4-7ad6-401c-ae92-829dae28ccb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>87680ec6-fae3-4fb4-adce-402e6c0d3ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>5d2c3d96-b8c1-417b-a804-d5e931fdb10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>99883752-4767-46d5-a495-b79153004450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac2af5a4-3e8c-45d5-b729-51254c3e92d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>combo_menu_combobox_item_0</value>
      <webElementGuid>096597c3-c6d9-46ee-8578-3c5223628f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combo_txt_combobox_item_0&quot;)</value>
      <webElementGuid>cf84f562-04fa-441e-b568-3fc536f0b475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combo_txt_combobox_item_0']</value>
      <webElementGuid>8379178d-e90f-4143-a6b4-30587373f3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='items-section']/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>4cb86186-cbc5-4e6b-be51-b86e60ba80f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>48d704e0-e1e8-4c11-a841-bf8cdafe9999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'combo_t_NO_NAME' and @id = 'combo_txt_combobox_item_0']</value>
      <webElementGuid>e4776be4-6e26-44de-8559-f146829d42d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
