<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quantity_unit_price</name>
   <tag></tag>
   <elementGuidId>381e38cf-31da-4cf8-888a-57c6fc3a204d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unit_price_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unit_price_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1e3cffd-fabe-40c8-a4a3-dbd55e8ffaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_text-input__control___3-14-1</value>
      <webElementGuid>faa166b5-5357-4d58-9456-27d3ee3c69d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unit_price</value>
      <webElementGuid>67177b25-e64c-4a53-87f9-43d0ea4f7de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unit_price_0</value>
      <webElementGuid>bb4530c8-6e17-47f1-95a9-ad1067e1edc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e5da80a6-91ae-4c1c-ac54-877932b2c05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern</name>
      <type>Main</type>
      <value>^-?[0-9]*[.]?[0-9]{0,2}$</value>
      <webElementGuid>61600dba-b3be-47a6-b4ee-541e9673358e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0a836624-60f9-4099-bf6a-a8b4ce531521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-minval</name>
      <type>Main</type>
      <value>-1000000</value>
      <webElementGuid>534a6f27-48f2-4d62-be04-d28a7ff7ba8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maxval</name>
      <type>Main</type>
      <value>1000000</value>
      <webElementGuid>fd860a49-9e0b-4f78-8593-e4535dbcb1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9e97ce18-737e-429e-8019-a0e0c77cb925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unit_price_0&quot;)</value>
      <webElementGuid>7e3e662a-5e39-415f-8d91-f73d70ef002c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unit_price_0']</value>
      <webElementGuid>77c3ac7c-724e-4473-be4a-0725a7cb274a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='items-section']/div[2]/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>98f5b6d8-659d-444d-813b-86dea1576aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c618321f-5e91-4403-8995-39e4d164da61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'unit_price' and @id = 'unit_price_0']</value>
      <webElementGuid>8569d883-926b-420d-90d3-5bcf77197971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
