<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill multiple customers_combo_t_email-input</name>
   <tag></tag>
   <elementGuidId>f58704d7-bd50-4127-9ba8-a255bd70811f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combo_txt_recipient-input-combobox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='combo_txt_recipient-input-combobox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35d05cee-c037-4f1d-9807-66566f8bac3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_text-input__control___3-14-1 ppvx_text-input__control--icon-right___3-14-1</value>
      <webElementGuid>3f04154f-0036-48c4-8222-cf270d00aa5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>combo_t_email-input</value>
      <webElementGuid>671ccb52-4178-4bd6-99ce-0e723999fa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combo_txt_recipient-input-combobox</value>
      <webElementGuid>09f507d1-0012-4dc3-a954-cdfd510cf87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af9bd8ce-1ca2-49f7-8256-c17d2551bae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>2c0a9712-dd77-4dee-8504-91d8031df602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>c7fc484d-aa39-4aba-8100-abee134c65d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc3d8eca-70ed-49fc-843e-c8cdbb147297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9d1dbfff-2bcf-46e0-8f4d-1875c58047ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>combo_menu_recipient-input-combobox</value>
      <webElementGuid>382f4927-34af-4b87-ac9b-01bb3b121381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combo_txt_recipient-input-combobox&quot;)</value>
      <webElementGuid>dbe03f10-d8d3-4cc0-95bf-693b83151a19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combo_txt_recipient-input-combobox']</value>
      <webElementGuid>eb18ef62-447c-4c99-a391-060ef099d3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[3]/div/div/div/div[2]/div[3]/div/div/div/div/input</value>
      <webElementGuid>ea2676fa-9919-490d-b1c4-3d3909a6b4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ce15bcf0-c362-4790-b8d9-5eb566c5c7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'combo_t_email-input' and @id = 'combo_txt_recipient-input-combobox']</value>
      <webElementGuid>8259eb3e-317b-41a5-bf97-6a297bbd3ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
