<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_John Doe</name>
   <tag></tag>
   <elementGuidId>a03c3c81-91da-4dff-a2d3-dbb3882859da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='merchant-header-main-wrapper-internal']/div/div/div[2]/div[3]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f84500ac-021c-4a4c-8602-abc4f6c0b2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>header_sub_fullName</value>
      <webElementGuid>ea0b6c9b-6b1f-4a2a-8d97-46b705dfd0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>John Doe</value>
      <webElementGuid>a6aae865-bb73-4dff-902c-84326012ca36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merchant-header-main-wrapper-internal&quot;)/div[1]/div[1]/div[2]/div[3]/div[1]/div[@class=&quot;css-1kw7e3e&quot;]/div[2]</value>
      <webElementGuid>c8dcd219-e1b3-442f-ab49-103d29f8a177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='merchant-header-main-wrapper-internal']/div/div/div[2]/div[3]/div/div/div[2]</value>
      <webElementGuid>6bfbb623-0e9b-4d56-9522-f13a4c526f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::div[6]</value>
      <webElementGuid>d1d8f902-c74d-4352-a2a2-6efa4bcdb744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Developer'])[1]/following::div[7]</value>
      <webElementGuid>050fb495-2b74-44d4-8ab7-273ed84a6c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Settings'])[1]/preceding::div[1]</value>
      <webElementGuid>248027a5-0aec-4bd5-98c2-6474feb20218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Settings'])[1]/preceding::div[1]</value>
      <webElementGuid>00147fd1-a534-4c3e-8d64-30f9745e54b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='John Doe']/parent::*</value>
      <webElementGuid>dbb61e94-49d4-48cb-8857-13088c5f02d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>a53570e0-7623-4632-840b-29d342c296aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'John Doe' or . = 'John Doe')]</value>
      <webElementGuid>aaa0d6e7-ea14-4902-a6ac-6bc03214a93d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
