<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log Masuk</name>
   <tag></tag>
   <elementGuidId>94d8a3a9-7dac-4d7a-8ff5-c6507ca4265e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ul-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ul-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>45164ebc-14d3-4b67-93e6-0ff8d915d215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ul-btn</value>
      <webElementGuid>f961b397-4715-452c-9133-09d7377e1305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.sandbox.paypal.com/signin</value>
      <webElementGuid>041ac3f0-518b-4730-b822-c0a0dfdd55f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pypl-btn mpp-btn pypl-btn--outline-white pypl-btn--small</value>
      <webElementGuid>d69ff2ca-af53-4d7f-bfa5-2c02e9127638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-click</name>
      <type>Main</type>
      <value>{&quot;link&quot;: &quot;HeaderMainMenu0-Cta-Log Masuk&quot;,&quot;event_name&quot;:&quot;ppcom_header_login_clicked&quot;}</value>
      <webElementGuid>b9a59e79-92e7-4e8c-a700-b8989c141622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>8d811576-9084-4346-92d1-9e6bf8a834bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dd47fcba-e631-4d1d-86dc-cded35f43971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log Masuk</value>
      <webElementGuid>16035bb9-ba5f-4b18-bbce-bbfa1e289d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ul-btn&quot;)</value>
      <webElementGuid>9d853cb3-0c83-4ff0-b413-0084c0b108f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ul-btn']</value>
      <webElementGuid>6ab06dfc-13bd-4400-a4bd-ae9057c0af4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-buttons']/div/a</value>
      <webElementGuid>dfd14edb-17ef-47e2-a949-97d10bff9d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log Masuk')]</value>
      <webElementGuid>5614a839-5bba-4c03-b1b6-f269fc694689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar secara Percuma'])[1]/following::a[1]</value>
      <webElementGuid>a3fb1abc-6b65-47f4-8820-5a8c9c21a373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cegah penipuan dalam talian'])[1]/following::a[3]</value>
      <webElementGuid>f9f79f6c-c556-4a19-aef7-895aace779fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>d384abf6-204a-46c3-8ee1-4ac7dd0ead65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Sales'])[1]/preceding::a[3]</value>
      <webElementGuid>7804f012-336b-4818-9f02-b039e510adef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log Masuk']/parent::*</value>
      <webElementGuid>637c9844-7e1c-4d9a-a2aa-3c0ebc783e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.sandbox.paypal.com/signin')]</value>
      <webElementGuid>cfd0ae24-a6de-4f9d-989e-998066a49c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>ce724d16-eaaa-4ead-a5df-3e6e18f1fab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ul-btn' and @href = 'https://www.sandbox.paypal.com/signin' and (text() = 'Log Masuk' or . = 'Log Masuk')]</value>
      <webElementGuid>4c12f669-c744-40f2-a682-4d63d94837b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
