<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log Masuk</name>
   <tag></tag>
   <elementGuidId>b9b10fc2-a3e3-47dc-a036-2b88f2acfe46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ul-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ul-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc57fb96-cf18-469f-8a8d-1f344ea234cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ul-btn</value>
      <webElementGuid>01c772c2-5193-4aa5-a26f-fbcd002fcfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.sandbox.paypal.com/signin</value>
      <webElementGuid>d3a5ec34-160a-435e-af91-d8278fb6b7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pypl-btn mpp-btn pypl-btn--outline-white pypl-btn--small</value>
      <webElementGuid>eb7daacc-bf7a-4d9c-b93e-48d7cfd42a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-click</name>
      <type>Main</type>
      <value>{&quot;link&quot;: &quot;HeaderMainMenu0-Cta-Log Masuk&quot;,&quot;event_name&quot;:&quot;ppcom_header_login_clicked&quot;}</value>
      <webElementGuid>a659c35b-5c17-42a8-88c5-e9cd400f55e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>379223d0-1c08-4475-8820-15e6155158b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>15160779-ac6e-4168-a785-ed4e77805d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log Masuk</value>
      <webElementGuid>70c70b29-00eb-412e-ace4-7216afe16029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ul-btn&quot;)</value>
      <webElementGuid>0dd9aac0-b0ad-4659-9df8-40c48d13cc74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ul-btn']</value>
      <webElementGuid>d98ffa54-769a-4095-b51f-8423ddc9ccb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-buttons']/div/a</value>
      <webElementGuid>50f236b3-8030-4a1d-aaea-2a3072d64ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log Masuk')]</value>
      <webElementGuid>f4113ac9-939c-468e-8c0a-33012d402f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar secara Percuma'])[1]/following::a[1]</value>
      <webElementGuid>0f27ef16-a103-4593-91f8-5dec059cdc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cegah penipuan dalam talian'])[1]/following::a[3]</value>
      <webElementGuid>e38c4bd8-e858-4f5c-bd3d-487c212a724c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>d730b275-657d-467c-bff3-6e3dbf7a4353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Sales'])[1]/preceding::a[3]</value>
      <webElementGuid>865e726b-5515-4652-817b-e54269ac7661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log Masuk']/parent::*</value>
      <webElementGuid>bef6514a-42ac-4bb9-9cc1-e60f40b054bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.sandbox.paypal.com/signin')]</value>
      <webElementGuid>da857069-d70e-4ab4-80a9-a12192aef98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>c324ddc4-d9ba-4b6f-b4e3-1a1fa3ffc985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ul-btn' and @href = 'https://www.sandbox.paypal.com/signin' and (text() = 'Log Masuk' or . = 'Log Masuk')]</value>
      <webElementGuid>7e6b2be6-d73e-4e54-b349-fd3c5753a5de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
