<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_English</name>
   <tag></tag>
   <elementGuidId>556d1190-c9f1-4ae3-bee7-69a9c3bf6538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>47c5bbf9-f640-4e09-89a2-14829ad4598e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> scTrack:unifiedlogin-footer-language_en_US</value>
      <webElementGuid>3ea10b39-d966-4bd1-ba9c-e3e7fa760160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en</value>
      <webElementGuid>bde136c3-9244-4a10-92e0-220fc5cc424a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>94a81224-97ac-4c8a-92e4-89d468adc1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locale</name>
      <type>Main</type>
      <value>en_US</value>
      <webElementGuid>7a36a6a5-8a27-415c-86cf-9206427b9f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8eb56d04-6bb9-4de4-8dcc-9bfb49dabf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>da1f0f1c-6363-41ec-856f-16695317b788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;intentFooter&quot;]/div[@class=&quot;localeSelector&quot;]/ul[@class=&quot;localeLink&quot;]/li[2]/a[@class=&quot;scTrack:unifiedlogin-footer-language_en_US&quot;]</value>
      <webElementGuid>34d3f007-8129-4af5-ac2a-db6d8684e3c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>27c92b60-cefd-4c51-9b35-b8775a7ad8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'English')])[2]</value>
      <webElementGuid>ed0db67c-66ab-4c8a-95d4-9ff36b189ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Melayu'])[2]/following::a[1]</value>
      <webElementGuid>898be2a1-a320-4f4f-a231-723e5041dbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benarkan log masuk menggunakan peranti mudah alih'])[2]/following::a[2]</value>
      <webElementGuid>92de7b9b-e8f2-45e6-aaa9-aa2ef68f188b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuba cara lain'])[2]/preceding::a[1]</value>
      <webElementGuid>78176275-b1c4-403d-ad2b-60a612f7b1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log masuk dengan muka, cap jari atau PIN'])[1]/preceding::a[1]</value>
      <webElementGuid>14f124de-5187-4d9e-bd67-6dd51fead80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en')])[2]</value>
      <webElementGuid>cbd412da-d525-48bc-bfd8-48f9c98e391a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>00c77715-dc57-4e15-8971-a2f39465bf8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>d374eed7-ab3d-4c8f-aff0-2a2a0ed7aba2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
