<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_English</name>
   <tag></tag>
   <elementGuidId>903a670f-a4d4-4bcd-8b0d-fbf38ad5c9a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4317b125-ef05-4724-bb37-0632a8ef6747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> scTrack:unifiedlogin-footer-language_en_US</value>
      <webElementGuid>3b3a0e48-464e-42c4-8ea6-b9eb8c19f72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en</value>
      <webElementGuid>b4e7e8ae-8483-4ee3-b483-eec9fef79668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>9c91a18e-26a2-42c4-9760-650e47a48419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locale</name>
      <type>Main</type>
      <value>en_US</value>
      <webElementGuid>4c9b51a7-7404-4d37-afd4-f0c926255a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>05c234f9-1c5e-4b79-8a18-00b483ae74f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>06345713-cd1a-4a98-9c3f-75f8e801b3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;intentFooter&quot;]/div[@class=&quot;localeSelector&quot;]/ul[@class=&quot;localeLink&quot;]/li[2]/a[@class=&quot;scTrack:unifiedlogin-footer-language_en_US&quot;]</value>
      <webElementGuid>4ebe37db-50f6-4441-9057-662376313737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>5cb6f7a5-0870-4af4-8e59-151c6d3063b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'English')])[2]</value>
      <webElementGuid>f7d4d719-05fc-4b66-9e84-3f3441d48fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Melayu'])[2]/following::a[1]</value>
      <webElementGuid>8f5173c3-a54e-48f3-a7dd-18467bbb86d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benarkan log masuk menggunakan peranti mudah alih'])[2]/following::a[2]</value>
      <webElementGuid>5fca5e05-cbf7-436f-b994-2fb4980418b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuba cara lain'])[2]/preceding::a[1]</value>
      <webElementGuid>040abcef-600d-4d1f-93cf-ec8512cc9521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log masuk dengan muka, cap jari atau PIN'])[1]/preceding::a[1]</value>
      <webElementGuid>0a38b01e-6828-44f1-bd95-8ed4fe365928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en')])[2]</value>
      <webElementGuid>1dd244dd-43af-4ff9-b864-2c027f1d5b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>3108b50d-d771-4e54-a8f7-f968f0e667da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>96ce9048-3c22-4110-883b-3d7e91ea739e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
