<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_589A4529-8063-4CAA-B3A7-46DACC69259ECre_cf718e</name>
   <tag></tag>
   <elementGuidId>c7fa5377-439b-4b29-a533-6ae55e708fb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='downshift-0-item-0']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-66t19h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3fdca870-741e-46a4-978c-16dbc8b5a451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemtype</name>
      <type>Main</type>
      <value>PHONE_OR_EMAIL</value>
      <webElementGuid>a3beff27-6c56-4efb-a244-f121b1c7d7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-66t19h</value>
      <webElementGuid>a5556148-2d75-48e6-9d31-518e96bc4079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>589A4529-8063-4CAA-B3A7-46DACC69259ECreated with sketchtool. Send to: nawwarahyusof123@gmail.com</value>
      <webElementGuid>402fe5bb-bfff-4086-af71-4f74f29b8c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-0-item-0&quot;)/div[@class=&quot;css-66t19h&quot;]</value>
      <webElementGuid>f9dff5ce-bb08-40b9-8b25-b1940901cfb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='downshift-0-item-0']/div</value>
      <webElementGuid>76fcefdc-a57c-4ab8-a7d4-f728f9eaa244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name, @username, email, or mobile'])[1]/following::div[6]</value>
      <webElementGuid>4b65736b-d789-49d2-81f2-b4af8c1c9d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send payment to'])[1]/following::div[11]</value>
      <webElementGuid>d41f8240-ef7c-4bc5-9731-137fe4606aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::div[1]</value>
      <webElementGuid>1376dd0f-93fa-4bd5-b03e-6d9b6ead01c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send to: nawwarahyusof123@gmail.com']/parent::*</value>
      <webElementGuid>9912453a-4ea3-491b-8428-8d1b624f0a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div/div/div</value>
      <webElementGuid>d12d50d8-8483-4c8a-b9d3-0461fb125d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '589A4529-8063-4CAA-B3A7-46DACC69259ECreated with sketchtool. Send to: nawwarahyusof123@gmail.com' or . = '589A4529-8063-4CAA-B3A7-46DACC69259ECreated with sketchtool. Send to: nawwarahyusof123@gmail.com')]</value>
      <webElementGuid>3c13e662-31aa-4d36-a490-da76fc9185a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
