<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log Masuk</name>
   <tag></tag>
   <elementGuidId>38000fd9-4de0-43ad-a729-667b2422e60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ul-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ul-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c43aa9b-0260-4f64-a0dd-d232cd89496c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ul-btn</value>
      <webElementGuid>4ca90f59-a5c5-4c26-b494-9ace4ccfd648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.sandbox.paypal.com/signin</value>
      <webElementGuid>74ff4eb1-fdb3-495d-ba02-e045666d5aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pypl-btn mpp-btn pypl-btn--outline-white pypl-btn--small</value>
      <webElementGuid>4e7c6a5c-18b5-47a8-8fc1-7bdcfd3c0fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pa-click</name>
      <type>Main</type>
      <value>{&quot;link&quot;: &quot;HeaderMainMenu0-Cta-Log Masuk&quot;,&quot;event_name&quot;:&quot;ppcom_header_login_clicked&quot;}</value>
      <webElementGuid>c9eeadb3-7ee6-4cee-ad67-0daaa717f8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>e03d0f44-d521-404d-bca0-42a1b04f2457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>02ef66e1-7c9a-4088-919b-9f5fd5d5ed46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log Masuk</value>
      <webElementGuid>654cbd1a-e637-413d-8d71-593c38e01204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ul-btn&quot;)</value>
      <webElementGuid>b932e55e-3c67-4c9b-abec-4bffae5d5fe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ul-btn']</value>
      <webElementGuid>85e33112-7aac-4342-bb46-a56966947be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-buttons']/div/a</value>
      <webElementGuid>bfc0796c-f59a-4942-b9c8-9d91b3180c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log Masuk')]</value>
      <webElementGuid>b9492bff-e7ab-4d4f-afeb-1bac070e57aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar secara Percuma'])[1]/following::a[1]</value>
      <webElementGuid>96d104c5-ad3b-4b0f-ab2b-d5ff971728ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cegah penipuan dalam talian'])[1]/following::a[3]</value>
      <webElementGuid>f1de1476-632f-48a3-8773-e6af461fc0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>8ef38f9a-13c0-400d-89b7-5c7f34159a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Sales'])[1]/preceding::a[3]</value>
      <webElementGuid>4889db50-25ce-4226-8d70-f546a8949bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log Masuk']/parent::*</value>
      <webElementGuid>9a1bb95d-db56-44ea-a228-eae2cc92b1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.sandbox.paypal.com/signin')]</value>
      <webElementGuid>992b1352-da79-4d92-b3d5-5a57771d4c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>21b70333-42d5-4bc7-8a1a-50c04f878d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ul-btn' and @href = 'https://www.sandbox.paypal.com/signin' and (text() = 'Log Masuk' or . = 'Log Masuk')]</value>
      <webElementGuid>ce6c7ad6-ddce-44fd-a831-70c48807bcb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
