<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_English</name>
   <tag></tag>
   <elementGuidId>ffab6131-10cd-4643-bc7c-0edf3b236463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc02ee8b-65cf-4395-ab5a-465e7b85dc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> scTrack:unifiedlogin-footer-language_en_US</value>
      <webElementGuid>36a561cd-6861-4d3d-a4c2-2b4b773ab692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en</value>
      <webElementGuid>5d67df34-7e38-4cdf-bb3d-8b3fdcdf0721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>ea6db4f0-f3f3-4fba-9075-9b152d590839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locale</name>
      <type>Main</type>
      <value>en_US</value>
      <webElementGuid>51112cac-b805-4056-9a47-70427ab084c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>99fe9031-961c-4b5f-8454-1614efaff582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>5bd70018-b924-4fae-a834-844e4411a717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;intentFooter&quot;]/div[@class=&quot;localeSelector&quot;]/ul[@class=&quot;localeLink&quot;]/li[2]/a[@class=&quot;scTrack:unifiedlogin-footer-language_en_US&quot;]</value>
      <webElementGuid>844b301b-d85d-4f65-a397-e5f0e269530f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>8081bff1-5184-48c5-8b63-7c8de6313427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'English')])[2]</value>
      <webElementGuid>fb2c0ec5-c900-478e-a0f0-d20edbb78d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Melayu'])[2]/following::a[1]</value>
      <webElementGuid>df5c09d8-b4bf-4e7e-8211-298f5b38a445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benarkan log masuk menggunakan peranti mudah alih'])[2]/following::a[2]</value>
      <webElementGuid>7114e61b-8f8d-4c44-8d75-b9052b415ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuba cara lain'])[2]/preceding::a[1]</value>
      <webElementGuid>cdaafaab-ca48-4392-b5d7-0b9896ba509d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log masuk dengan muka, cap jari atau PIN'])[1]/preceding::a[1]</value>
      <webElementGuid>eea3916b-e488-4efb-a7dd-90398ef13ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en')])[2]</value>
      <webElementGuid>d72cff54-3ce6-4636-b464-585ec885fc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>004fd4f3-36d4-417c-8ad5-0ef3acbed063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>574a9ebf-f181-46db-a84f-f321a2de78a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
