<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Request a Payment</name>
   <tag></tag>
   <elementGuidId>836f0dac-4872-43b6-838c-bb5eed380e15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.css-y7b5t5.vx_btn.preview-btn.preview-requestMoney.validateBeforeSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>033a37e5-ce01-45d6-a558-feaedb5769a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9d8b6e78-f396-43bb-ae04-c87f1e050fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99525566-6615-43fa-a8c4-ffa75e015967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>00273851-a997-48b3-95df-156871fb4e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-y7b5t5 vx_btn preview-btn preview-requestMoney validateBeforeSubmit</value>
      <webElementGuid>381d913e-3360-49f2-b043-2b4ed5bec0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request a Payment</value>
      <webElementGuid>4bbc0e05-f2d2-4f12-9973-78147f160ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-transfer-container&quot;)/div[@class=&quot;react-p2p_wrapper css-1e4troo&quot;]/div[1]/div[@class=&quot;css-4x2c91&quot;]/form[@class=&quot;css-nil transferPage request previewPage&quot;]/div[@class=&quot;preview-buttons&quot;]/button[@class=&quot;css-y7b5t5 vx_btn preview-btn preview-requestMoney validateBeforeSubmit&quot;]</value>
      <webElementGuid>92df97bd-fae7-424f-8a05-ac19d993a3cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>2809b34f-6cdf-4915-8d3e-1ec9056071ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/div/form/div[2]/button</value>
      <webElementGuid>83c9116b-8390-44cf-83e8-6ae9b1942ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add someone else?'])[1]/following::button[1]</value>
      <webElementGuid>709f352a-b16f-480b-a99a-d71b3f9cdf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Center'])[1]/following::button[2]</value>
      <webElementGuid>2620c5b1-1b09-4e15-96a6-5f6dc9dba7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>28e12e07-3fe5-4650-b184-57f154900e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[2]/preceding::button[2]</value>
      <webElementGuid>632d0a35-9a3c-459f-80fd-4edc19cf1fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request a Payment']/parent::*</value>
      <webElementGuid>eb33642e-9ed7-4afa-878c-f33ea642f8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>f2e4c1ee-1ef7-41fd-b34d-4ccccd2e84b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Request a Payment' or . = 'Request a Payment')]</value>
      <webElementGuid>c115efbc-cc90-4ef0-9291-a5b6c4ce89e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
