<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_App Center_amount</name>
   <tag></tag>
   <elementGuidId>784873b9-0dc3-4725-83ed-f8bf464c46ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fn-amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fn-amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>056e957d-b375-437d-be87-30acd365baa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>enter amount field</value>
      <webElementGuid>07d3f08c-4477-4c1f-aa30-6e2b787e0a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>ed5a794b-0ac8-4eb6-b979-b51ddd40658e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>fb7008f7-e31b-49f3-9bbc-a4f6b217f774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amount</value>
      <webElementGuid>49ed8ded-72a4-4ecf-b9b3-a239909cf3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nemo</name>
      <type>Main</type>
      <value>amount</value>
      <webElementGuid>5d4c7af5-ed57-4d2b-ac14-6df6f119e54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fn-amount</value>
      <webElementGuid>c1511eff-f2cf-4c99-a655-75cd0030629b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>602d9057-e592-41b9-9850-1544ad8b2902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-65d4bq</value>
      <webElementGuid>1536c5f4-532e-4361-8807-98994947f768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>9aec4e6d-7320-4858-869a-c0df33ca0f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fn-amount&quot;)</value>
      <webElementGuid>ed145f4d-784e-421a-8b7e-06b237dfccce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fn-amount']</value>
      <webElementGuid>cdada384-e2fc-4d4c-b821-346f43590f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-transfer-container']/div/div/div/form/div/div/div/input</value>
      <webElementGuid>eeadad59-b187-454f-bce3-acbc911a1d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d61f28c7-f794-4480-9e8f-4d00ef626aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'amount' and @id = 'fn-amount']</value>
      <webElementGuid>f5b16802-d19e-448f-a1e6-2872f0b38efd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
