<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_English</name>
   <tag></tag>
   <elementGuidId>e2fed723-8d36-437d-84dc-c9d4805cde8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>47f97ee6-125f-4278-b2cb-70a7f461b5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> scTrack:unifiedlogin-footer-language_en_US</value>
      <webElementGuid>e2f9cd02-2b70-4ff2-abf4-74611f39fe57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en</value>
      <webElementGuid>ebfc97d8-e2e3-46da-a3ac-c5b921531380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>918492eb-7ec2-445b-9637-311f4d5aedfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locale</name>
      <type>Main</type>
      <value>en_US</value>
      <webElementGuid>770d9fa7-7b62-429c-9608-eea7b3a0d08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pa-marked</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>84844b43-70fb-4e21-add8-dbf1f05e5014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>defde29c-e7f2-4ef3-adf4-192b11eb063b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;intentFooter&quot;]/div[@class=&quot;localeSelector&quot;]/ul[@class=&quot;localeLink&quot;]/li[2]/a[@class=&quot;scTrack:unifiedlogin-footer-language_en_US&quot;]</value>
      <webElementGuid>f94499e1-8075-4d66-9933-2b5b4afc8e3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>be6d3ef5-951b-4f75-abd7-e5d467efa9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'English')])[2]</value>
      <webElementGuid>bb0fce99-fac7-4c4d-a5b8-4bf2d14966ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Melayu'])[2]/following::a[1]</value>
      <webElementGuid>2a71e02d-aa20-4f53-96eb-be86364c93c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benarkan log masuk menggunakan peranti mudah alih'])[2]/following::a[2]</value>
      <webElementGuid>f20ea23a-7794-43d7-82aa-8f8e8fc63493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuba cara lain'])[2]/preceding::a[1]</value>
      <webElementGuid>a098112a-df3e-42fb-9456-34df5c8b1121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log masuk dengan muka, cap jari atau PIN'])[1]/preceding::a[1]</value>
      <webElementGuid>bf42928b-7615-4386-8a47-551cd4bc3e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en')])[2]</value>
      <webElementGuid>30b36abd-32f8-4dee-9152-159c72e66235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>6a53591a-b324-4097-b77f-78f5b6b5c867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/signin?country.x=MY&amp;locale.x=en_US&amp;langTgl=en' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>eb66f1bd-867d-4c32-a88a-f9d322fe5971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
